# Generated by Django 4.2.7 on 2024-03-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymoney', '0002_delete_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysafedata',
            name='photo',
        ),
    ]
