# Generated by Django 4.2.7 on 2024-03-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mymoney', '0006_category_alter_moneysafedata_price_moneysafedata_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneysafedata',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Mymoney.category'),
        ),
    ]
